version: "3.9"

services:
  chat_app_db:
    image: postgres:14-alpine
    container_name: chat_app_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - chat_app_network
    restart: unless-stopped

  chat_app_service:
    container_name: chat_app_service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/go/src/chat_app_service
    ports:
      - "8000:8000"
    depends_on:
      - chat_app_db
    networks:
      - chat_app_network
    links:
      - chat_app_db
    environment:
      GOPATH: /go/
    restart: on-failure
    tty: true


networks:
  chat_app_network:
    driver: bridge

volumes:
  pg_data: